version: '3.8'
services:
  frontend:
    image: node:18.2.0-slim
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - backend

  backend:
    image: maven:3.8.5-jdk-11
    working_dir: /app
    volumes:
      - ./backend:/app
    command: mvn spring-boot:run -Dspring-boot.run.profiles=dev
    ports:
      - "8080:8080"